### ISSUE TITLE
操作列表最后一个数据时会报错

### ISSUE THREAD

**Issue by mrchenmo** [LinXunFeng/flutter_scrollview_observer#10]
RenderBox.size accessed beyond the scope of resize, layout, or permitted parent access. RenderBox can always access its own size, otherwise, the only object that is allowed to read RenderBox.size is its parent, if they have said they will. It you hit this assert trying to access a child's size, pass "parentUsesSize: true" to that child's layout().
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1937 pos 13: 'debugDoingThisResize || debugDoingThisLayout || _computingThisDryLayout ||
              (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)'

**Comment by LinXunFeng** [comment]
麻烦请提供demo或可复现问题的代码

**Comment by mrchenmo** [comment]
![O3JF `HP IJM4CWG8{4 K2V](https://user-images.githubusercontent.com/18020929/187326440-801b053c-59ab-4c6d-8598-c24d0aabea45.png)
这是最外面的代码
ListViewObserver(
                        //controller: observerController,
                        child: ListView.builder(
                          shrinkWrap: true,
                          physics: ClampingScrollPhysics(),
                          itemCount: dataList.length,
                          controller: scrollController,
                          itemBuilder: (BuildContext context, int index) {
                            return OrderPickDetailItem(
                              position: index,
                              item: dataList[index],
                              scroll: scrollController,
                            );
                          },
                        ),
                        onObserve: (ListViewObserveModel resultModel) {
                     
                        },
                      ),
这是OrderPickDetailItem里面增加库位按钮的代码
 tempDepotList.add(SkuPosition(
              recommendPositionNo: '宁波港西南片区新增库位',
              recommendPositionId: 41800 + 1,
              depotNameController: TextEditingController(text: '宁波港西南片区新增库位'),
            ));
            widget.item.skuPosition = tempDepotList;
            widget.scroll?.jumpTo(widget.scroll!.offset + 42.0);
         
            setState(() {});

**Comment by mrchenmo** [comment]
具体的报错信息

When the exception was thrown, this was the stack: 
#2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1937:13)
#3      RenderBox.size (package:flutter/src/rendering/box.dart:1950:6)
#4      ObserverWidgetState.isTargetFirstWidget (package:scrollview_observer/src/common/observer_widget.dart:199:28)
#5      ListObserverMix.handleListObserve (package:scrollview_observer/src/listview/list_observer_mix.dart:50:13)
#6      ListViewObserverState.handleObserve (package:scrollview_observer/src/listview/list_observer_view.dart:63:12)
#7      ObserverWidgetState._handleContexts (package:scrollview_observer/src/common/observer_widget.dart:153:34)
#8      ObserverWidgetState.build.<anonymous closure> (package:scrollview_observer/src/common/observer_widget.dart:89:11)
#9      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:206:42)
#10     Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:122:20)
#11     ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
#12     Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4133:39)
#13     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:138:13)
#14     ScrollActivity.dispatchScrollEndNotification (package:flutter/src/widgets/scroll_activity.dart:104:63)
#15     ScrollPosition.didEndScroll (package:flutter/src/widgets/scroll_position.dart:906:15)
#16     ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:875:9)
#17     ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:114:11)
#18     ScrollPositionWithSingleContext.goIdle (package:flutter/src/widgets/scroll_position_with_single_context.dart:129:5)
#19     ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:148:7)
#20     BallisticScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:549:14)
#21     ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:622:15)
#22     ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:104:11)
#23     ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:552:7)
#24     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1894:55)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#41     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#45     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#47     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#48     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896:45)
#49     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#51     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#52     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#53     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#55     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#57     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#58     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097:7)
#59     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#60     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#61     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713:7)
#62     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
#63     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
#64     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#65     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#66     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#67     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#68     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#72     _invoke (dart:ui/hooks.dart:166:10)
#73     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#74     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderShrinkWrappingViewport#fd26b relayoutBoundary=up14
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=360.0, h=453.0)
...  layer: OffsetLayer#04277
...    engine layer: OffsetEngineLayer#518b1
...    handles: 2
...    offset: Offset(0.0, 0.0)
...  size: Size(360.0, 453.0)
...  axisDirection: down
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#e68b5(offset: 165.0, range: 0.0..338.0, viewport: 453.0, ScrollableState, ClampingScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e2bc1, ScrollDirection.idle)
RenderObject: RenderShrinkWrappingViewport#fd26b relayoutBoundary=up14
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=360.0, h=453.0)
  layer: OffsetLayer#04277
    engine layer: OffsetEngineLayer#518b1
    handles: 2
    offset: Offset(0.0, 0.0)
  size: Size(360.0, 453.0)
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#e68b5(offset: 165.0, range: 0.0..338.0, viewport: 453.0, ScrollableState, ClampingScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e2bc1, ScrollDirection.idle)
...  child 0: RenderSliverPadding#cf85f relayoutBoundary=up15
...    needs compositing
...    parentData: layoutOffset=0.0 (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 165.0, remainingPaintExtent: 453.0, crossAxisExtent: 360.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 453.0, remainingCacheExtent: 868.0, cacheOrigin: -165.0)
...    geometry: SliverGeometry(scrollExtent: 791.0, paintExtent: 453.0, maxPaintExtent: 791.0, hasVisualOverflow: true, cacheExtent: 791.0)
...      scrollExtent: 791.0
...      paintExtent: 453.0
...      maxPaintExtent: 791.0
...      hasVisualOverflow: true
...      cacheExtent: 791.0
...    padding: EdgeInsets.zero
...    textDirection: ltr
...    child: RenderSliverList#a39e9 relayoutBoundary=up16
...      needs compositing
...      parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...      constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 165.0, remainingPaintExtent: 453.0, crossAxisExtent: 360.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 453.0, remainingCacheExtent: 868.0, cacheOrigin: -165.0)
...      geometry: SliverGeometry(scrollExtent: 791.0, paintExtent: 453.0, maxPaintExtent: 791.0, hasVisualOverflow: true, cacheExtent: 791.0)
...        scrollExtent: 791.0
...        paintExtent: 453.0
...        maxPaintExtent: 791.0
...        hasVisualOverflow: true
...        cacheExtent: 791.0
...      currently live children: 0 to 2
...      child with index 0: RenderIndexedSemantics#82820 relayoutBoundary=up17
...        needs compositing
...        parentData: index=0; layoutOffset=0.0 (can use size)
...        constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
...        semantics node: SemanticsNode#88
...          STALE
...          owner: null
...          Rect.fromLTRB(0.0, 0.0, 360.0, 28.6)
...          tags: RenderViewport.twoPane
...          actions: tap
...          flags: isImage
...          label: "排序测试3

**Comment by LinXunFeng** [comment]
你把 `ListViewObserver` 移除掉会报这些错吗？

**Comment by mrchenmo** [comment]
> 
不包裹 ListViewObserver应该不会报错

**Comment by LinXunFeng** [comment]
请你确认是不是该库引起的问题，如果是，请提供 `Demo` 和复现步骤，节省大家的时间，感谢

**Comment by mrchenmo** [comment]
> 
可以，等我忙完了这段事件，我写个demo看看能不能复现。感谢

**Comment by mrchenmo** [comment]
> 请你确认是不是该库引起的问题，如果是，请提供 `Demo` 和复现步骤，节省大家的时间，感谢

我换了个写法，使用起来又不报错了，不过我还是有方法复现那个错误，等几天我写个demo试下。

**Comment by LinXunFeng** [comment]
好的 : )

**Comment by xiaodogaa** [comment]
> > 请你确认是不是该库引起的问题，如果是，请提供 `Demo` 和复现步骤，节省大家的时间，感谢
> 
> 我换了个写法，使用起来又不报错了，不过我还是有方法复现那个错误，等几天我写个demo试下。

怎么写的，我这边也出现了，

**Comment by xiaodogaa** [comment]
我是 SliverViewObserver->NotificationListener<ScrollEndNotification>->EasyRefresh->CustomScrollView

**Comment by xiaodogaa** [comment]
在你的Example上也复现了，在CustomScrollViewDemoPage里按照上面的层级关系，初次进入是正常的，当刷新时，就会报错
修改如下：
Widget _buildScrollView() {
    return NotificationListener<ScrollEndNotification>(
      onNotification: (ScrollEndNotification notification) {
        setState(() {});
        return false;
      },
      child: EasyRefresh(
        onRefresh: () async {
          await Future.delayed(Duration(seconds: 3));
        },
        child: CustomScrollView(
          controller: scrollController,
          // scrollDirection: Axis.horizontal,
          slivers: [
            SliverToBoxAdapter(
              child: Container(
                height: 36,
                color: Colors.blue,
              ),
            ),
            _buildSliverListView(),
            _buildSliverGridView(),
          ],
        ),
      ),
    );
  }

**Comment by LinXunFeng** [comment]
> 在你的Example上也复现了，在CustomScrollViewDemoPage里按照上面的层级关系，初次进入是正常的，当刷新时，就会报错 修改如下： Widget _buildScrollView() { return NotificationListener( onNotification: (ScrollEndNotification notification) { setState(() {}); return false; }, child: EasyRefresh( onRefresh: () async { await Future.delayed(Duration(seconds: 3)); }, child: CustomScrollView( controller: scrollController, // scrollDirection: Axis.horizontal, slivers: [ SliverToBoxAdapter( child: Container( height: 36, color: Colors.blue, ), ), _buildSliverListView(), _buildSliverGridView(), ], ), ), ); }

我使用了你贴出来的代码，并加了如下依赖，下拉刷新并没有报错

```dart
easy_refresh: ^3.0.4+2
```

你集成的是旧版的 `easy_refresh` ？

**Comment by LinXunFeng** [comment]
我使用了 `flutter_easyrefresh: ^2.2.2` 出现了你们所说的这个问题，这个 `v2` 版本根据作者的 `README` 显示已经不再维护，升级到 `v3` 可解决，你们升级看看吧

**Comment by xiaodogaa** [comment]
感谢，升级 easy_refresh就可以了

**Comment by mrchenmo** [comment]
我写了个Demo来复现问题，作者大大，麻烦看下。https://github.com/mrchenmo/test_ob

**Comment by LinXunFeng** [comment]
> 我写了个Demo来复现问题，作者大大，麻烦看下。https://github.com/mrchenmo/test_ob

@mrchenmo 
> [Size](https://api.flutter.dev/flutter/dart-ui/Size-class.html) size
> This value is stale whenever this object is marked as needing layout. During [performLayout](https://api.flutter.dev/flutter/rendering/RenderBox/performLayout.html), do not read the size of a child unless you pass true for parentUsesSize when calling the child's [layout](https://api.flutter.dev/flutter/rendering/RenderBox/layout.html) function. -- 取自[【官方文档】](https://api.flutter.dev/flutter/rendering/RenderBox/size.html)
 > 不要在布局的时候去读取 `RenderBox` 的 `size`！

你在 `setState` 时调用了 `jumpTo` 方法，进而触发了该库去监听计算当前列表中的 `widget` 相关信息，这里面有获取 `size` 的操作，你可以按如下代码做调整：

```dart
WidgetsBinding.instance.addPostFrameCallback((_) {
  widget.scroll?.jumpTo(widget.scroll!.offset + 42.0);
});
```

**Comment by mrchenmo** [comment]
> 

在setState 时会导致页面重建，这时候去滚动列表触发了库获得孩子的信息，其实这个时候页面并没有完全重建完毕，导致获取Size信息报错。这样理解对吗。我想能不能创建个FAQ文档，把这些使用不规范的问题记录下。

**Comment by mrchenmo** [comment]
确实是这个问题导致的，感谢作者抽时间解决我饿得问题，谢谢。

**Comment by LinXunFeng** [comment]
`1.5.1` 版本已对此做了处理，两位可以不用改代码或升级 `EasyRefresh`，感谢你们的反馈 🤠
