### ISSUE TITLE
聊天列表场景问题

### ISSUE THREAD

**Issue by a1239897580** [LinXunFeng/flutter_scrollview_observer#13]
根据案例代码编写，正常情况下没问题。
但是案例代码中是直接点击按钮插入的消息，少了一种情况。当主动发消息时，是需要键盘弹起的，这个时候滑动视图的最大高度和展示高度都发生了改变。发完消息就会发生错误。
standby方法中的observeSwitchShrinkWrap方法发生错误被捕捉，插件版本1.6.2-67行。报错如下
![image](https://user-images.githubusercontent.com/70512922/201612401-2ef340a1-2d39-49b6-9e22-51fbc82b2aa8.png)
这个报错倒是没影响视图，影响视图的是另一个问题。isShrinkWrap变量错误的被设置。当键盘弹起的时候，最大高度变小，仅需几条消息即可超过最大高度可以滚动。键盘弹起后，发送消息或者收到消息会调用插入与standby并刷新视图，这个时候isShrinkWrap就会被标记为false，当键盘回收时，最大高度恢复，这个时候应当为true才是正确的。
刚接触大佬的代码哈，可能有点描述的不清楚

**Comment by LinXunFeng** [comment]
感谢反馈，不过这个 `setState` 理论上是可以替换成指定局部刷新 `ListView` 的，不需要整个页面刷新

**Comment by a1239897580** [comment]
还是这个问题，键盘弹起的时候被设置为false后，收起键盘又设置为true，视图会发生闪动，掉下来又拉上去一瞬间还是挺明显的

**Comment by a1239897580** [comment]
![image](https://user-images.githubusercontent.com/70512922/201883053-a2468d53-aaed-4b52-92de-50ccce670297.png)
退出页面或者切换键盘，感觉可能是因为测试机比较卡还是干嘛的视图释放有问题导致的。这个点能否优化一下

**Comment by LinXunFeng** [comment]
是否可以提供一份 `Demo` 方便我调试？还是说示例就可以触发？

**Comment by a1239897580** [comment]
不好意思哈。平时没咋上git。这个问题不是必现的，等我找到原因了再来反馈

**Comment by LinXunFeng** [comment]
> 遇到了个问题。 ![image](https://user-images.githubusercontent.com/70512922/203282642-ba45f12f-33ef-43f9-9e7d-169ff5a3819b.png) 关键代码是这样的 ![image](https://user-images.githubusercontent.com/70512922/203282792-6e2bb760-1cc8-41ba-922f-e1fd28d49ca7.png) 移除这部分代码的话就是正常的。 看这个报错似乎是不能使用BoxConstraints还是和我的用法哪里冲突了

这部分内容应该不是该库引起的吧？光看你给出的这部分代码我也无法确定问题，这个需要你自己排查下咯

**Comment by a1239897580** [comment]
observerController的定位指定下标功能，是定位到底部的。怎么操作可以让他定位到头部吗
