### ISSUE TITLE
SliverPersistentHeader遮挡

### ISSUE THREAD

**Issue by zyk-miao** [LinXunFeng/flutter_scrollview_observer#15]
我的应用有 SliverAppBar，SliverPersistentHeader 我看示例有关于offset偏移SliverAppBar的 ，那么请问SliverPersistentHeader的有吗

**Comment by LinXunFeng** [comment]
一样支持的，你直接把 SliverAppBar 换 `SliverPersistentHeader` 就可以了

**Comment by zyk-miao** [comment]
SliverAppBar，SliverPersistentHeader 都存在也可以吗

**Comment by LinXunFeng** [comment]
你的场景是有多个可变大小的视图？

**Comment by zyk-miao** [comment]
就是一个CustomScrollView 的slivers里面放的一个SliverAppBar一个SliverPersistentHeader一个SliverList，我滚动的时候被SliverPersistentHeader遮住了

**Comment by zyk-miao** [comment]
我的意思是jumpto的offset可以偏移SliverAppBar，那么可以能否同时偏移SliverAppBar和SliverPersistentHeader吗

**Comment by LinXunFeng** [comment]
你在调用 `animateTo` 时在 `offset` 回调内返回 `SliverAppBar` 和 `SliverPersistentHeader` 的高度即可

```dart
observerController.animateTo(
  sliverContext: _sliverListCtx,
  index: 8,
  duration: const Duration(milliseconds: 300),
  curve: Curves.easeInOut,
  offset: (offset) {
    return ObserverUtils.calcPersistentHeaderExtent(
          key: appBarKey,
          offset: offset,
        ) +
        ObserverUtils.calcPersistentHeaderExtent(
          key: persistentHeaderKey,
          offset: offset,
        );
  },
);
```

**Comment by zyk-miao** [comment]
好的好的 谢谢您～
