### ISSUE TITLE
ListViewObserver下 onObserve 偶现不回调

### ISSUE THREAD

**Issue by MarsHou** [LinXunFeng/flutter_scrollview_observer#16]
场景：TabBar 结合 ListViewObserver->ListView 使用，数据量是超过了两屏的
操作：点击tab，获取tab index，执行controller.jumpTo(index)或者controller.animateTo(index), 特定情况下没有进入onObserve回调
特定情况：listview cellIndex=0  再执行controller.jumpTo(index)，index =3，jumpTo 跳转正常。但是onObserve没有回调。
其它情况都正常：只要index 不是3，都能正常回调onObserve，或者 cellIndex >0 的情况，执行controller.jumpTo  也能正常回调onObserve。

**Comment by LinXunFeng** [comment]
示例代码是否可以复现？如不能是否方便提供 `Demo` ？

**Comment by MarsHou** [comment]
> 

  Widget _listView() {
    if (controller.tabController?.hasListeners == false) {
      controller.tabController?.addListener(() {
        final index = controller.tabController?.index ?? 0;
        if (index == controller.tabController?.animation?.value) {
          controller.state?.tabIndex.value = index;
          Log.d("-------click:$index");
          controller.listObserverController.jumpTo(index: index);
        }
      });
    }
    var list = []..length = controller.state?.captionList.length ?? 8;

    var data = list
        .asMap()
        .map((index, element) => MapEntry(index, "data$index"))
        .values
        .toList();
    return Container(
      child: Column(
        children: [
          Obx(() => AllAppsTabBar(
                data,
                tabController: controller.tabController,
                selectIndex: controller.state?.tabIndex.value ?? 0,
              )),
          Expanded(
              child: ListViewObserver(
            controller: controller.listObserverController,
            onObserve: (resultModel) {
              final cellIndex = resultModel.firstChild?.index ?? 0;
              Log.d("-------cellIndex:$cellIndex");
            },
            child: ListView.builder(
              controller: controller.scrollController,
              physics: const BouncingScrollPhysics(),
              itemBuilder: (context, index) {
                return InkWell(
                  onTap: () {},
                  child: Container(
                    child: Text("data:$index"),
                    height: 400 + 10.0 * index,
                    color: Colors.blue,
                  ),
                );
              },
              itemCount: data.length,
            ),
          ))
        ],
      ),
    );
  }



我复现的时候，发现主要原因是cell 的高度，足够高的时候，容易复现。利用上面的代码 点击tab data3 ，就能看到日志 只输出了 -------click:3

**Comment by LinXunFeng** [comment]
你把 `jumpTo` 放到 `TabBar` 的 `onTap` 中去调用
```dart
TabBar(
  controller: tabController,
  tabs: tabs
      .mapIndexed((index, element) => Tab(text: '$index'))
      .toList(),
  onTap: (index) {
    print("-------click:$index");
    observerController.jumpTo(index: index);
  },
)
```

**Comment by MarsHou** [comment]
> 你把 `jumpTo` 放到 `TabBar` 的 `onTap` 中去调用
> 
> ```dart
> TabBar(
>   controller: tabController,
>   tabs: tabs
>       .mapIndexed((index, element) => Tab(text: '$index'))
>       .toList(),
>   onTap: (index) {
>     print("-------click:$index");
>     observerController.jumpTo(index: index);
>   },
> )
> ```

awesome thanks! 👍
