### ISSUE TITLE
带上偏移量会出现的若干问题

### ISSUE THREAD

**Issue by H-Bin** [LinXunFeng/flutter_scrollview_observer#17]
感谢大佬的插件，但是在结合我的业务需求使用时发现了一些问题，我的页面是一个stack，第一个子组件是ListViewObserver，叠加在顶部的是一个随滑动从透明变不透明的tabbar。
出现的问题是：
1.tabbar里的  observerController.animateTo(）如果添加了offset
```
onTap: (value) {
                  observerController.animateTo(
                    index: value,
                    duration: const Duration(milliseconds: 250),
                    curve: Curves.ease,
                    offset: (offset) {
                      return TAB_HEIGHT;
                    },
                  );
                },
```
listviewObserver里同时添加onObserver,在点击tab时大概率会出现tab切换错误，tab会在切换到目标tab之后跳到目标tab的上一个位置，并且offset好像并没有生效，还是有tabbar height的偏移错误
```
onObserve: (resultModel) {
            _tabController.index = ObserverUtils.calcAnchorTabIndex(
              observeModel: resultModel,
              tabIndexs: tabIndexs,
              currentTabIndex: _tabController.index,
            );
          },
```

2.在我去掉onObserver后，点击tab偏移量基本正常，但是在第一个标签和最后一个标签来回切换的时候，第一次能准确定位到最后一个标签，之后定位就会定位错误（但是一个个标签点过去就不会出错）
                   

下面附上demo
<details>
  <summary><mark><font color=darkred>查看代码</font></mark></summary>
  <pre><code>  
/*
 * @Author: LinXunFeng linxunfeng@yeah.net
 * @Repo: https://github.com/LinXunFeng/flutter_scrollview_observer
 * @Date: 2022-08-08 00:20:03
 */
import 'package:flutter/material.dart';
import 'package:scrollview_observer/scrollview_observer.dart';

class AnchorListPage extends StatefulWidget {
  const AnchorListPage({Key? key}) : super(key: key);

  @override
  State<AnchorListPage> createState() => _AnchorListPageState();
}

class _AnchorListPageState extends State<AnchorListPage>
    with SingleTickerProviderStateMixin {
  ScrollController scrollController = ScrollController();

  late ListObserverController observerController;
  late TabController _tabController;
  List tabs = ["0", "1", "2", "3", "4"];
  List<int> tabIndexs = [0, 1, 2, 3, 4];
  double TAB_HEIGHT = 48;
  double opacity = 0.0;
  GlobalKey tabbarKey = GlobalKey();
  List<double> containerHeight = [310, 210, 400, 270, 1000];

  @override
  void initState() {
    super.initState();
    observerController = ListObserverController(controller: scrollController);
    _tabController = TabController(length: tabs.length, vsync: this);
    scrollController.addListener(() => _onScrollChanged());
  }

  @override
  void dispose() {
    observerController.controller?.dispose();
    _tabController.dispose();
    super.dispose();
  }

  /// 滑动事件
  void _onScrollChanged() {
    /// 滑动显示tabbar的触发距离
    double showTabBarOffset = 350;

    // 滑动距离大于触发距离时显示tabbar
    if (scrollController.offset >= showTabBarOffset) {
      setState(() {
        opacity = 1;
      });
    } else {
      // 滑动距离小于触发距离显示动态透明度
      setState(() {
        opacity = scrollController.offset / showTabBarOffset;
        if (opacity < 0) {
          opacity = 0;
        }
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('demo')),
      body: Stack(children: [
        ListViewObserver(
          controller: observerController,
          child: _buildListView(),
          // onObserve: (resultModel) {
          //   _tabController.index = ObserverUtils.calcAnchorTabIndex(
          //     observeModel: resultModel,
          //     tabIndexs: tabIndexs,
          //     currentTabIndex: _tabController.index,
          //   );
          // },
        ),
        Positioned(
          top: 0,
          height: TAB_HEIGHT,
          child: Opacity(
            opacity: opacity,
            key: tabbarKey,
            child: Container(
              color: Colors.white,
              width: MediaQuery.of(context).size.width,
              height: TAB_HEIGHT,
              child: TabBar(
                controller: _tabController,
                tabs: tabs.map((e) => Tab(text: e)).toList(),
                labelColor: Colors.black,
                onTap: (value) {
                  observerController.animateTo(
                    index: value,
                    duration: const Duration(milliseconds: 250),
                    curve: Curves.ease,
                    offset: (offset) {
                      // return ObserverUtils.calcPersistentHeaderExtent(
                      //   key: tabbarKey,
                      //   offset: offset,
                      // );
                      return TAB_HEIGHT;
                    },
                  );
                },
              ),
            ),
          ),
        ),
      ]),
    );
  }

  ListView _buildListView() {
    return ListView.separated(
      controller: scrollController,
      itemBuilder: (ctx, index) {
        return _buildListItemView(index);
      },
      separatorBuilder: (ctx, index) {
        return _buildSeparatorView();
      },
      itemCount: tabIndexs.length,
    );
  }

  Widget _buildListItemView(int index) {
    Widget item = Container();

    switch (index) {
      case 0:
        item = Container(
          height: 565,
          color: Colors.red,
          child: Center(
            child: Text('index -- $index'),
          ),
        );

        break;
      case 1:
        item = Container(
          height: 207,
          color: Colors.red,
          child: Center(
            child: Text('index -- $index'),
          ),
        );
        break;
      case 2:
        item = Container(
          height: 262,
          color: Colors.red,
          child: Center(
            child: Text('index -- $index'),
          ),
        );
        break;
      case 3:
        item = Container(
          height: 400,
          color: Colors.red,
          child: Center(
            child: Text('index -- $index'),
          ),
        );
        break;
      case 4:
        item = Container(
          height: 1000,
          color: Colors.red,
          child: Center(
            child: Text('index -- $index'),
          ),
        );
        break;
    }

    return item;
  }

  Container _buildSeparatorView() {
    return Container(
      color: Colors.white,
      height: 5,
    );
  }
}
  </code></pre>
</details>

**Comment by LinXunFeng** [comment]
```dart
ListViewObserver(
  controller: observerController,
  child: _buildListView(),
  leadingOffset: TAB_HEIGHT,
  onObserve: (resultModel) {
    _tabController.index = ObserverUtils.calcAnchorTabIndex(
      observeModel: resultModel,
      tabIndexs: tabIndexs,
      currentTabIndex: _tabController.index,
    );
  },
),
```

**Comment by H-Bin** [comment]
确实解决了前几个组件的定位问题，但是最后一个组件还是会出问题，复现方法：反复点击 0 和 4 tab（4虽然不可见，但是那个位置还是可以点击的），第一次能准确定位到4，第二次之后会出现上述描述的第一种情况，tab indicator 会从4 跳到3

**Comment by LinXunFeng** [comment]
你们这个的使用场景是在有限模块数量的详情页下吗？建议设置 `cacheExtent` 为无限大
```dart
ListView.separated(
  ...
  cacheExtent: double.maxFinite,
);
```
上面的定位不准是 `Flutter` 中 `viewport` 给的最大可偏移量有问题导致的

**Comment by H-Bin** [comment]
是的，目前模块数是有限的，但模块高度是不确定的

**Comment by LinXunFeng** [comment]
OK，后面我会调整一下代码解决这个小问题。

但因为你是详情页这类页面，所以还是建议你设置 `cacheExtent`（不用等新版本），具体说明可以查看这里：[滚动到指定下标位置](https://github.com/LinXunFeng/flutter_scrollview_observer/blob/main/README-zh.md#2%E6%BB%9A%E5%8A%A8%E5%88%B0%E6%8C%87%E5%AE%9A%E4%B8%8B%E6%A0%87%E4%BD%8D%E7%BD%AE)

**Comment by LinXunFeng** [comment]
请升级使用 `1.9.1` 版本

**Comment by H-Bin** [comment]
ok，我升级试试，多谢大佬
