### ISSUE TITLE
不支持上拉加载

### ISSUE THREAD

**Issue by JDongKhan** [LinXunFeng/flutter_scrollview_observer#19]
您好，使用该组件实现chat效果时，发现几个问题。1、数据量大的时候很卡，2、好像不支持第三方的上拉加载，比如pull_to_refresh。
```dart
import 'package:easy_refresh/easy_refresh.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:scrollview_observer/scrollview_observer.dart';

import '../controller/doctor_chat_controller.dart';

class ChartListWidget extends StatefulWidget {
  const ChartListWidget({
    Key? key,
    required this.itemBuilder,
    required this.itemCount,
    this.scrollController,
  }) : super(key: key);
  final IndexedWidgetBuilder itemBuilder;
  final int itemCount;
  final ScrollController? scrollController;
  @override
  State<ChartListWidget> createState() => _ChartListWidgetState();
}

class _ChartListWidgetState extends State<ChartListWidget> {
  final EasyRefreshController _refreshController = EasyRefreshController(
    controlFinishRefresh: true,
    controlFinishLoad: true,
  );

  late ListObserverController observerController;
  late ChatScrollObserver chatObserver;
  late ScrollController _scrollController;
  final DoctorChatController _controller = Get.find<DoctorChatController>();
  @override
  void initState() {
    _scrollController = widget.scrollController ?? ScrollController();
    observerController = ListObserverController(controller: _scrollController)
      ..cacheJumpIndexOffset = false;

    chatObserver = ChatScrollObserver(observerController)
      ..fixedPositionOffset = 5
      ..toRebuildScrollViewCallback = () {
        setState(() {});
      }
      ..onHandlePositionCallback = (type) {};

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return _buildListView();
  }

  Widget _buildListView() {
    Widget resultWidget = EasyRefresh(
      onRefresh: () async {
        await _controller.onRefresh();
        _refreshController.finishRefresh();
      },
      onLoad: () async {
        await _controller.onLoad();
        _refreshController.finishLoad();
      },
      header: const CupertinoHeader(),
      footer: const CupertinoFooter(),
      child: ListView.builder(
        physics: ChatObserverBouncingScrollPhysics(observer: chatObserver),
        padding:
            const EdgeInsets.only(left: 10, right: 10, top: 15, bottom: 15),
        shrinkWrap: chatObserver.isShrinkWrap,
        reverse: true,
        controller: _scrollController,
        itemBuilder: widget.itemBuilder,
        itemCount: widget.itemCount,
      ),
    );

    resultWidget = ListViewObserver(
      controller: observerController,
      child: resultWidget,
    );
    resultWidget = Align(
      alignment: Alignment.topCenter,
      child: resultWidget,
    );
    return resultWidget;
  }
}

```

**Comment by LinXunFeng** [comment]
你好，感觉反馈，不过问题需要麻烦你那边确认一下
1、数据量大的时候很卡：你那边列表视图是不是有调整 `cacheExtent`？希望能把相关代码发上来看看
2、好像不支持第三方的上拉加载：我还没有尝试过第三方的刷新控件，但是 `pull_to_refresh` 已经两年没有更新了，它有可能是造成卡顿的原因，或许可以试试看这个 [flutter_easy_refresh](https://github.com/xuelongqy/flutter_easy_refresh)

**Comment by JDongKhan** [comment]
> 你好，感觉反馈，不过问题需要麻烦你那边确认一下
> 1、数据量大的时候很卡：你那边列表视图是不是有调整 `cacheExtent`？希望能把相关代码发上来看看
> 2、好像不支持第三方的上拉加载：我还没有尝试过第三方的刷新控件，但是 `pull_to_refresh` 已经两年没有更新了，它有可能是造成卡顿的原因，或许可以试试看这个 [flutter_easy_refresh](https://github.com/xuelongqy/flutter_easy_refresh)

多谢，试了下，去掉pull_to_refresh卡顿的问题确实好多了，但是
1、chatObserver.isShrinkWrap一直是true，这个没影响吗？
2、我这边使用了[flutter_easy_refresh](https://github.com/xuelongqy/flutter_easy_refresh)还是不能上拉。

**Comment by LinXunFeng** [comment]
1、`chatObserver.isShrinkWrap` 会在 `standby` 方法被调用时更新，`standby` 方法应该在插入或删除数据时手动调用，你一直为 `true` 是不是因为你没有调 `standby` 这个方法？

这里随带提一点，`shrinkWrap` 一直为 `true` 时并不意味着所有的 `itemView` 会被渲染，它只是决定了没有高度约束时列表视图的高度。

2、我这边试了一下 [flutter_easy_refresh](https://github.com/xuelongqy/flutter_easy_refresh)，它不支持自定义 `physics`，而我的插入消息时固定当前位置的方案需要自定义 `physics`~，如果你不需要固定消息位置的话可以去掉 `physics`，这样你就可以用这个刷新控件了，如果要保留，那就需要重新找一个支持自定义 `physics` 的刷新控件，或者自己写这种刷新控件(`itemCount: chatList.length+1`)

这里记录一下可用的刷新控件：

- [custom_refresh_indicator](https://pub.dev/packages/custom_refresh_indicator)
```dart
resultWidget = CustomRefreshIndicator(
  child: resultWidget,
  builder: MaterialIndicatorDelegate(
    builder: (context, controller) {
      return Icon(
        Icons.ac_unit,
        color: Colors.blue,
        size: 30,
      );
    },
  ),
  trigger: IndicatorTrigger.trailingEdge,
  onRefresh: () {
    return Future.delayed(Duration(seconds: 2));
  },
);
```

- [liquid_pull_to_refresh](https://pub.dev/packages/liquid_pull_to_refresh)

注：这个不支持 `reverse`，需要你自己手动对数据进行反转

```dart
resultWidget = LiquidPullToRefresh(
  onRefresh: () {
    return Future.delayed(Duration(seconds: 2));
  }, // refresh callback
  child: resultWidget, // scroll view
  showChildOpacityTransition: false,
);
```

**Comment by JDongKhan** [comment]
嗯，多谢，我不需要消息提示，去掉就可以了。

**Comment by LinXunFeng** [comment]
不是消息提示哦，是插入新消息时固定当前的消息位置，比如你当前下拉到第二、三条消息后，插入新的消息在最底下，此时列表会被往上顶

**Comment by JDongKhan** [comment]
> 不是消息提示哦，是插入新消息时固定当前的消息位置，比如你当前下拉到第二、三条消息后，插入新的消息在最底下，此时列表会被往上顶

... 那这个需要哎，目前去掉physics[flutter_easy_refresh](https://github.com/xuelongqy/flutter_easy_refresh)能正常使用。

你推荐的[custom_refresh_indicator](https://pub.dev/packages/custom_refresh_indicator)没有onLoad，因为reverse需要的是加载更多功能，而listview不能reverse也不行，我之前就是用的CustomScrollView,因为没有reverse导致键盘弹起被挡住，体验差别就出来了。

**Comment by LinXunFeng** [comment]
聊天页一般只需要加载历史信息吧？即下拉，[custom_refresh_indicator](https://pub.dev/packages/custom_refresh_indicator) 可以设置`trigger: IndicatorTrigger.trailingEdge` 切换方向，也算是够用，你们有上下拉共存的场景？

**Comment by JDongKhan** [comment]
没有上下拉共存的场景，多谢，我试试。

**Comment by CatEatFishs** [comment]
上拉有场景，比如我搜索聊天记录，进入页面是搜索的某一条消息，此时应该有上拉加载历史数据。

**Comment by LinXunFeng** [comment]
其实 [custom_refresh_indicator](https://pub.dev/packages/custom_refresh_indicator) 这个库通过设置`trigger: IndicatorTrigger.bothEdges` 即可实现上下拉功能 : )

```dart
Widget resultWidget = ListView.builder(
  ...
);

resultWidget = CustomRefreshIndicator(
  trigger: IndicatorTrigger.bothEdges,
  leadingScrollIndicatorVisible: false,
  trailingScrollIndicatorVisible: false,
  builder: MaterialIndicatorDelegate(
    builder: (context, controller) {
      return Icon(
        Icons.ac_unit,
        color: Theme.of(context).colorScheme.primary,
        size: 30,
      );
    },
  ),
  onRefresh: () => Future.delayed(const Duration(seconds: 2)),
  child: resultWidget,
);
```

**Comment by LinXunFeng** [comment]
❗ ❗ ❗ 纠正:

支持结合 [flutter_easy_refresh](https://github.com/xuelongqy/flutter_easy_refresh) 使用，示例代码如下

```dart
Widget _buildListView() {
  return EasyRefresh.builder(
    header: const MaterialHeader(),
    footer: const MaterialFooter(),
    // footer: ClassicFooter(
    //   position: IndicatorPosition.above,
    //   infiniteOffset: null,
    // ),
    onRefresh: () async {
      await Future.delayed(Duration(seconds: 2));
    },
    onLoad: () async {
      await Future.delayed(Duration(seconds: 2));
    },
    childBuilder: (context, physics) {
      Widget resultWidget = ListView.builder(
        // 重点
        physics: physics.applyTo(ChatObserverClampingScrollPhysics(observer: chatObserver)),

        shrinkWrap: chatObserver.isShrinkWrap,
        reverse: true,
        controller: scrollController,
        itemBuilder: ((context, index) {
          return ChatItemWidget(
            ...
          );
        }),
        itemCount: chatModels.length,
      );

      resultWidget = ListViewObserver(
        controller: observerController,
        child: resultWidget,
      );

      // 使包裹于 Expanded 下的 ListView 能正常显示在顶部
      resultWidget = Align(
        child: resultWidget,
        alignment: Alignment.topCenter,
      );
      return resultWidget;
    },
  );
}
```

**Comment by dabugge** [comment]
> ❗ ❗ ❗ 纠正:
> 
> 支持结合 [flutter_easy_refresh](https://github.com/xuelongqy/flutter_easy_refresh) 使用，示例代码如下
> 
> ```dart
> Widget _buildListView() {
>   return EasyRefresh.builder(
>     header: const MaterialHeader(),
>     footer: const MaterialFooter(),
>     // footer: ClassicFooter(
>     //   position: IndicatorPosition.above,
>     //   infiniteOffset: null,
>     // ),
>     onRefresh: () async {
>       await Future.delayed(Duration(seconds: 2));
>     },
>     onLoad: () async {
>       await Future.delayed(Duration(seconds: 2));
>     },
>     childBuilder: (context, physics) {
>       Widget resultWidget = ListView.builder(
>         // 重点
>         physics: physics.applyTo(ChatObserverClampingScrollPhysics(observer: chatObserver)),
> 
>         shrinkWrap: chatObserver.isShrinkWrap,
>         reverse: true,
>         controller: scrollController,
>         itemBuilder: ((context, index) {
>           return ChatItemWidget(
>             ...
>           );
>         }),
>         itemCount: chatModels.length,
>       );
> 
>       resultWidget = ListViewObserver(
>         controller: observerController,
>         child: resultWidget,
>       );
> 
>       // 使包裹于 Expanded 下的 ListView 能正常显示在顶部
>       resultWidget = Align(
>         child: resultWidget,
>         alignment: Alignment.topCenter,
>       );
>       return resultWidget;
>     },
>   );
> }
> ```

这个demo里面的footer和header如果使用`ClassicFooter`和`ClassicHeader` 在消息满了一屏幕后下拉就会出现只能触发`onLoad`方法一次，整个页面不会还原，一直处于onLoad状态。请问是啥原因呢？

**Comment by LinXunFeng** [comment]
我自己试着不会，这是我的代码

```dart
header: const ClassicHeader(),
footer: const ClassicFooter(
  position: IndicatorPosition.above,
  infiniteOffset: null,
),
```

**Comment by dabugge** [comment]
加了position和infiniteOffset属性就好了，厉害滴~

还有个问题请教一下：
按照demo中的代码来说，有两部分可以下拉，当消息只有一条的时候（不满一屏幕）可以点消息下拉，也可以点空白（消息下面部分）下拉，如果用第一种方式下拉会出现消息提前被覆盖，如下图：
![image](https://github.com/LinXunFeng/flutter_scrollview_observer/assets/97232806/513f4bf0-3185-4c14-ba3b-795150ef5b8f)

**Comment by LinXunFeng** [comment]
哦，被 `EasyRefresh` 的 `physics` 影响到了，你在 `childBuilder` 中调整一下 `physics`
```dart
// 新增的代码
var listViewPhysics =
    physics.applyTo(ChatObserverClampingScrollPhysics(
  observer: chatObserver,
));
if (chatObserver.isShrinkWrap) {
  listViewPhysics =
      const NeverScrollableScrollPhysics().applyTo(listViewPhysics);
}

Widget resultWidget = ListView.builder(
  physics: listViewPhysics, // 调整这里
  ...
);
```

**Comment by dabugge** [comment]
多谢，好使了！

**Comment by dabugge** [comment]
> 哦，被 `EasyRefresh` 的 `physics` 影响到了，你在 `childBuilder` 中调整一下 `physics`
> 
> ```dart
> // 新增的代码
> var listViewPhysics =
>     physics.applyTo(ChatObserverClampingScrollPhysics(
>   observer: chatObserver,
> ));
> if (chatObserver.isShrinkWrap) {
>   listViewPhysics =
>       const NeverScrollableScrollPhysics().applyTo(listViewPhysics);
> }
> 
> Widget resultWidget = ListView.builder(
>   physics: listViewPhysics, // 调整这里
>   ...
> );
> ```

这么做的话貌似还有点瑕疵哈，如果采用了`NeverScrollableScrollPhysics()`是不是意味着listview就成了一个column不能滚动了，那是不是消息永远只有一个屏幕，超出一个屏幕的消息将丢失了？

**Comment by LinXunFeng** [comment]
不会呀，有 `isShrinkWrap` 把控，在非 `isShrinkWrap` 的情况下就没有 `NeverScrollableScrollPhysics`，也没有 `SingleChildScrollView` 包裹，内部在超过一屏数据的时候会将 `chatObserver.isShrinkWrap` 转为 `false` 然后通过 `toRebuildScrollViewCallback` 让外部去更新列表视图

**Comment by dabugge** [comment]
了然啦, 我看叉劈了，哈哈哈，谢谢

**Comment by pokid** [comment]
> ```dart
> var listViewPhysics =
>     physics.applyTo(ChatObserverClampingScrollPhysics(
>   observer: chatObserver,
> ));
> if (chatObserver.isShrinkWrap) {
>   listViewPhysics =
>       const NeverScrollableScrollPhysics().applyTo(listViewPhysics);
> }
> ```

如果消息没请求返回前随便给一个组件，比如 SizedBox.shrink()，消息请求返回后再加载listview，这个case下好像确实不能滚动了

**Comment by pokid** [comment]
还有个问题就是，按照大佬的方式修改了listViewPhysics，easy refersh的下拉加载indicator不知道为啥一直会显示不会消失了。

**Comment by LinXunFeng** [comment]
> > ```dart
> > var listViewPhysics =
> >     physics.applyTo(ChatObserverClampingScrollPhysics(
> >   observer: chatObserver,
> > ));
> > if (chatObserver.isShrinkWrap) {
> >   listViewPhysics =
> >       const NeverScrollableScrollPhysics().applyTo(listViewPhysics);
> > }
> > ```
> 
> 如果消息没请求返回前随便给一个组件，比如 SizedBox.shrink()，消息请求返回后再加载listview，这个case下好像确实不能滚动了

不建议 listview 和其它组件切换显示，非得这么做就需要你自己在合适的时机去调用 `reattach`，具体说明可以看这个 [1.7、reattach](https://github.com/fluttercandies/flutter_scrollview_observer/wiki/1%E3%80%81%E7%9B%91%E5%90%AC%E6%BB%9A%E5%8A%A8%E8%A7%86%E5%9B%BE%E4%B8%AD%E6%AD%A3%E5%9C%A8%E6%98%BE%E7%A4%BA%E7%9A%84%E5%AD%90%E9%83%A8%E4%BB%B6#17reattach)

> 修改了listViewPhysics，easy refersh的下拉加载indicator不知道为啥一直会显示不会消失了。

这个问题可以看看这个回复 https://github.com/fluttercandies/flutter_scrollview_observer/issues/19#issuecomment-1689534440

**Comment by pokid** [comment]
> [custom_refresh_indicator](https://pub.dev/packages/custom_refresh_indicator)

明白了。我看上面有聊到上下拉，使用easy_refresh能实现吗，我试了下下拉没有问题，但是上拉就不能保持消息位置了，直接到第一条去了。。。

**Comment by LinXunFeng** [comment]
> > [custom_refresh_indicator](https://pub.dev/packages/custom_refresh_indicator)
> 
> 明白了。我看上面有聊到上下拉，使用easy_refresh能实现吗，我试了下下拉没有问题，但是上拉就不能保持消息位置了，直接到第一条去了。。。

`easy_refresh` 也可以的，你可以看看示例代码
