### ISSUE TITLE
聊天页面滚动跳动

### ISSUE THREAD

**Issue by Apach3Q** [LinXunFeng/flutter_scrollview_observer#25]
![image](https://user-images.githubusercontent.com/21135761/230298842-a75e6db7-cf0e-4711-b0e4-fa93a18cbeab.png)
在开发聊天页面的时候，Listview 的 reverse 设置为 true，即将展示的 item 有图片的时候滚动页面会跳动。请问有解决办法吗

**Comment by LinXunFeng** [comment]
希望能有复现问题，可运行的完整 `Demo`，光看这份代码截图，无法确认和定位问题。

我只能猜测是你的图片没有设置固定的宽高，待item出现后网络图片加载完毕，使item的尺寸发生变成，进而导致的页面跳动

**Comment by yasersojoodi** [comment]
hi. 
when i renew elements of a listView.builder() , jumpTo() dose not work. it dose not jump.
consider a listView by 100 elements. when i change element counts to 150, jumpTo() dose not work.
can you help me please?

**Comment by Apach3Q** [comment]
谢谢，已经解决了，图片需要设置宽高。
