### ISSUE TITLE
jumpTo() dose not work

### ISSUE THREAD

**Issue by yasersojoodi** [LinXunFeng/flutter_scrollview_observer#26]
hi.
when i renew elements of a listView.builder() , jumpTo() dose not work. it dose not jump.
consider a listView by 100 elements. when i change element counts to 150, jumpTo() dose not work.
can you help me please?

**Comment by LinXunFeng** [comment]
Could you please provide a reproducible demo?

**Comment by yasersojoodi** [comment]
hi.
i fixed it. it was my mistake. because after renewing list elements, ListObserverController  was rebuild by new ScrollController().
thanks.

**Comment by krishnaaroNowapps** [comment]
> hi. i fixed it. it was my mistake. because after renewing list elements, ListObserverController was rebuild by new ScrollController(). thanks. very usefull package ; )

what will be the fix please explain, I'm facing the same issue ...
