### ISSUE TITLE
亲爱的作者您好，想问一个问题，如何获取item的底部距离屏幕底部的距离。

### ISSUE THREAD

**Issue by mrchenmo** [LinXunFeng/flutter_scrollview_observer#3]
现在遇到个问题，在页面底部悬浮个按钮，悬浮在ListView之上，ListView的子部件里面的内容可以更改，当子控件的高度增加，视觉上第一个子控件已经到底了，真实是屏幕上还能展示两个子控件。因为底部多了个控件把ListView遮住了一部分

**Comment by LinXunFeng** [comment]
`develop` 分支添加了两个属性：`leadingAxisMarginToViewport` 和 `trailingAxisMarginToViewport`

```dart
onObserve: (resultModel) {
  for (var item in resultModel.displayingChildModelList) {
    print('item - ${item.index} - ${item.leadingAxisMarginToViewport} - ${item.trailingAxisMarginToViewport}');
  }
}
```

**Comment by mrchenmo** [comment]
> `develop` 分支添加了两个属性：`leadingMarginToViewport` 和 `trailingMarginToViewport`
> 
> ```dart
> onObserve: (resultModel) {
>   for (var item in resultModel.displayingChildModelList) {
>     print('item - ${item.index} - ${item.leadingMarginToViewport} - ${item.trailingMarginToViewport}');
>   }
> }
> ```
> 
> 你可以先进行分支依赖，看看这两个属性是否可以满足你的使用场景

OK，我是试试看

**Comment by mrchenmo** [comment]
@LinXunFeng 有取到数值，但我感觉不准，这个场景下先不管了，只要滑动功能是正常的。谢谢

**Comment by mrchenmo** [comment]
> `develop` 分支添加了两个属性：`leadingMarginToViewport` 和 `trailingMarginToViewport`
> 
> ```dart
> onObserve: (resultModel) {
>   for (var item in resultModel.displayingChildModelList) {
>     print('item - ${item.index} - ${item.leadingMarginToViewport} - ${item.trailingMarginToViewport}');
>   }
> }
> ```
> 
> 你可以先进行分支依赖，看看这两个属性是否可以满足你的使用场景

试了下因该是可以的

**Comment by LinXunFeng** [comment]
请更新使用 `1.2.0` 版本，感谢支持
