### ISSUE TITLE
scrolling  fast on web show bad index item 

### ISSUE THREAD

**Issue by rmasarovic** [LinXunFeng/flutter_scrollview_observer#31]
Hi i try your example and when i scroll fast with  mouse on web i see different item on screen and different values are printing on observer update

this is screen 
<img width="959" alt="image" src="https://github.com/LinXunFeng/flutter_scrollview_observer/assets/1522834/9a737733-6d51-46cf-b4ff-d51b3d44f80a">

and this is last print on console 
firstChild.index -- 14
displaying -- [14]
item - 14 - -20 - 456
visible -- true
firstChild.index -- 24
displaying -- [24]
item - 24 - -20 - 456

any idea what is wrong?

**Comment by LinXunFeng** [comment]
Thx for feedback, please upgrade to version `1.13.1`, or pull the latest code.

**Comment by rmasarovic** [comment]
i try it and when i using mouse wheel this index dont work 
<img width="958" alt="image" src="https://github.com/LinXunFeng/flutter_scrollview_observer/assets/1522834/b835883b-268b-4397-9c8a-bbe2ace287e4">
firstChild.index -- 51
displaying -- [51, 52, 53, 54, 55, 56, 57, 58]
item - 51 - -8.336594410433463 - 474.33659441043346
item - 52 - 46.66340558956654 - 389.33659441043346
item - 53 - 131.66340558956654 - 334.33659441043346
item - 54 - 186.66340558956654 - 249.33659441043346
item - 55 - 271.66340558956654 - 194.33659441043346
item - 56 - 326.66340558956654 - 109.33659441043346
item - 57 - 411.66340558956654 - 54.33659441043346
item - 58 - 466.66340558956654 - -30.663405589566537

**Comment by LinXunFeng** [comment]
It works fine on macos, this problem seems to only occur on windows.  🧐

**Comment by rmasarovic** [comment]
hm i try on mac and some
<img width="1438" alt="Snímka obrazovky 2023-06-03 o 15 46 32" src="https://github.com/LinXunFeng/flutter_scrollview_observer/assets/1522834/c0abdfc7-c85d-474e-bd40-5a9a24c0a59e">
i think this edge-case depence when use mouse wheel scroller

**Comment by LinXunFeng** [comment]
I have tried to fix this problem on the `fix_observe_web` branch and tested it, you can try it again after pulling the code.

**Comment by rmasarovic** [comment]
I tried it and out of 100 attempts, it failed 1 time, but I haven't find the pattern yet, but still it's perfect now. 

What else did I notice when I scroll a lot and then I go away from the page, the observer keeps printing values to console.  it normal behavior?
![image](https://github.com/LinXunFeng/flutter_scrollview_observer/assets/1522834/fee4bf5f-c65e-41c2-86d3-ceb4f448a037)

**Comment by LinXunFeng** [comment]
Yes, this is normal behavior, because there was a lot of printing in the Example, and the IDE did not process it in time.

This bug is caused by scrolling in Flutter Web with mouse wheel is not smooth.

Related issues:
- [#78708](https://github.com/flutter/flutter/issues/78708)
- [#78634](https://github.com/flutter/flutter/issues/78634)

The problem has not been solved yet, so for now, i use `delay` to solve it.

The key code is here: [observer_widget.dart#L148](https://github.com/LinXunFeng/flutter_scrollview_observer/blob/fix_observe_web/lib/src/common/observer_widget.dart#L148)
```dart
Future.delayed(const Duration(microseconds: 1), () {
```
Could you please replace `microseconds` with `milliseconds` in this line of code, and try it again?

```dart
Future.delayed(const Duration(milliseconds: 1), () {
```

**Comment by rmasarovic** [comment]
i try it and maybe this is the best solution for now

**Comment by LinXunFeng** [comment]
Thank you, version `1.13.2` has been released to fix the above issues.
