### ISSUE TITLE
监听滚动状态

### ISSUE THREAD

**Issue by 309791679** [LinXunFeng/flutter_scrollview_observer#32]
我想监听ListViewObserver执行的滚动状态例如，observerController.animateTo点击后提供
滚动开始、滚动进行中、滚动即将结束(不知道好不好实现)、滚动结束 @LinXunFeng

**Comment by LinXunFeng** [comment]
有两个疑问

- 监听这个是为了做什么？
- 使用 `NotificationListener` 去监听满足不了吗？

**Comment by LinXunFeng** [comment]
`1.18.0` 版本开始新增了滚动状态，相关说明：[2.9、滚动状态](https://github.com/fluttercandies/flutter_scrollview_observer/wiki/2%E3%80%81%E6%BB%9A%E5%8A%A8%E5%88%B0%E6%8C%87%E5%AE%9A%E4%B8%8B%E6%A0%87%E4%BD%8D%E7%BD%AE#29%E6%BB%9A%E5%8A%A8%E7%8A%B6%E6%80%81)
