### ISSUE TITLE
展示消息时间时，无法保留当前滚动位置的问题

### ISSUE THREAD

**Issue by wangyang3-ola** [LinXunFeng/flutter_scrollview_observer#33]
大佬，我这边聊天列表会展示消息时间，具体规则是 如果两条消息的发送时间的分钟数一样，则第二条消息不展示时间。
用这个组件在插入新的消息时， standy方法没有效果，还是会出现抖动的情况。
在您的demo里面类似加上以下代码，就会复现：
<img width="752" alt="image" src="https://github.com/LinXunFeng/flutter_scrollview_observer/assets/113671783/5a82b618-a087-4648-839d-0d9605f0c029">

**Comment by LinXunFeng** [comment]
你这样写有问题吧，会使旧的历史消息交替显示隐藏时间，理论上是不可能出现这种情况的，你们在实际场景下也是怎么处理时间的？

**Comment by wangyang3-ola** [comment]
渲染当前消息时，获取前一条消息的时间，判断分钟数一样的话，就不展示当前时间
<img width="977" alt="image" src="https://github.com/LinXunFeng/flutter_scrollview_observer/assets/113671783/9778502d-2dba-4837-893a-e3d3af8f1e9c">

**Comment by LinXunFeng** [comment]
你这样写应该是没问题的，至于 `standby` 不生效可能是其它原因，你可以先固定不显示时间，看看是否也会抖动？

**Comment by wangyang3-ola** [comment]
我搞错了，没有套上ListViewObserver组件，现在可以了。感谢

**Comment by LinXunFeng** [comment]
OK
