### ISSUE TITLE
如何实现目标不可见的时候才滚动定位？

### ISSUE THREAD

**Issue by feimenggo** [LinXunFeng/flutter_scrollview_observer#36]
目前调用observerController.animateTo会直接滚动定位，我想实现当index不可见的时候才滚动定位至可见，ListObserverController有没有方法判断index当前是否可见呢？

**Comment by LinXunFeng** [comment]
可以将 `onObserve` 回调中的观察结果保存起来，再通过判断 `displayingChildIndexList` 有没有目标 `index` 即可
