### ISSUE TITLE
demo里关于聊天演示，在第一次加载数据超过一屏的时候，下拉的时候isShrinkWrap是true，导致只能显示一部分数据

### ISSUE THREAD

**Issue by atiman** [LinXunFeng/flutter_scrollview_observer#47]
如果我增加一条数据，是调用了chatObserver.standby(changeCount: count)，然后scrollView_observer就把isShrinkWrap修改为了false，有什么办法在我第一次进入聊天，根据当前数据多少，来修改isShrinkWrap的值，现在貌似第一次进入聊天，isShrinkWrap都是true

**Comment by LinXunFeng** [comment]
可以在加载完数据并完成布局后手动触发一次观察，来校正 `isShrinkWrap`

```dart
WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
  chatObserver.observeSwitchShrinkWrap();
});
```

**Comment by atiman** [comment]
好的，解决了，谢谢

**Comment by LinXunFeng** [comment]
在 `1.16.5` 版本中，初始化时做了一次校正，不用再自己手动触发，请升级试试看吧
