### ISSUE TITLE
列表中插入大于15条数据，列表会自己跳动

### ISSUE THREAD

**Issue by xwdevhub** [LinXunFeng/flutter_scrollview_observer#50]
demo中chat_page.dart中按钮事件调用_addMessage方法，当数量大于15，插入数据后，offset异常，导致列表跳转。
我排查了一下，在observer_controller.dart中，通过findChildInfo获取targetChild存在问题，无法正确获取到targetChild导致列表变化

**Comment by LinXunFeng** [comment]
请参考 [3.1、基本使用](https://github.com/LinXunFeng/flutter_scrollview_observer/blob/main/README-zh.md#31%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8) 的最后一段描述
