### ISSUE TITLE
大佬, list里面的item组件高度变化后,跳转会有偏移

### ISSUE THREAD

**Issue by mdddj** [LinXunFeng/flutter_scrollview_observer#51]
这种有办法解决吗

**Comment by LinXunFeng** [comment]
默认有对偏移量进行缓存，可以选择关闭缓存功能，或者是更新高度后清除一次

- [2.6、cacheJumpIndexOffset 属性](https://github.com/LinXunFeng/flutter_scrollview_observer/wiki/2%E3%80%81%E6%BB%9A%E5%8A%A8%E5%88%B0%E6%8C%87%E5%AE%9A%E4%B8%8B%E6%A0%87%E4%BD%8D%E7%BD%AE#26cachejumpindexoffset-%E5%B1%9E%E6%80%A7)
- [2.7、clearIndexOffsetCache 方法](https://github.com/LinXunFeng/flutter_scrollview_observer/wiki/2%E3%80%81%E6%BB%9A%E5%8A%A8%E5%88%B0%E6%8C%87%E5%AE%9A%E4%B8%8B%E6%A0%87%E4%BD%8D%E7%BD%AE#27clearindexoffsetcache-%E6%96%B9%E6%B3%95)

**Comment by mdddj** [comment]
多谢大佬,有用
