### ISSUE TITLE
InitState Jump

### ISSUE THREAD

**Issue by cyb3rsalih** [LinXunFeng/flutter_scrollview_observer#6]
Hi! I face a problem about the package and wonder we can solve it or not.

I want to go a spesific index when I open my book.
After everything loaded, there is no problem I can go any page with enter number to method

`listObserverController.jumpTo(index: 13);`

But When I try to use it in initState, it just doesn't work. There is no error or anything. 

my initState like this
```dart
  void initState() {
    super.initState();
    bookModel = context.read<BookProvider>();
    _scrollController = ScrollController(initialScrollOffset: widget.book.lastIndex);
    listObserverController = ListObserverController(controller: _scrollController);
    _scrollController.addListener(() {
      //Save the pageIndex for next come.
      bookModel.setSavePage(widget.book, _scrollController.offset);
    });

    WidgetsBinding.instance.addPostFrameCallback((_) {

        listObserverController.jumpTo(index: 13);
      
    });
  };
  ```
  
  In first open, there is no move. When I reload the page with ctrl | cmd + S, `listObserverController.jumpTo(index: 13);` trigger and go the page.
  
  When  I don't use `WidgetsBinding.instance.addPostFrameCallback`  it doesn't work also.

**Comment by LinXunFeng** [comment]
```dart
_scrollController = ScrollController(initialScrollOffset: widget.book.lastIndex);
```
I think there's a mistake here, this is passing the initialization offset, not index.

The listview is not finished layout in `initState`, so you should use `WidgetsBinding.instance.addPostFrameCallback`

**Comment by cyb3rsalih** [comment]
Thanks, yes I am passing last offset to `initialScrollOffset` it's just naming mistake.
It still doesn't work 🤔

```dart
  void initState() {
    super.initState();
    bookModel = context.read<BookProvider>();
    _scrollController = ScrollController(initialScrollOffset: widget.book.lastOffset);
    _fihristScrollController = ScrollController();
    listObserverController = ListObserverController(controller: _scrollController);
    _scrollController.addListener(() {
      // Kaydetme fonksiyonuna gönderilecek.
      bookModel.setSavePage(widget.book, _scrollController.offset);
    });
    //Doesn't work
    WidgetsBinding.instance.addPostFrameCallback((_) {
      listObserverController.jumpTo(index: 13);
    });
  }
  ```

**Comment by LinXunFeng** [comment]
I think  the `listObserverController.jumpTo(index: 13);` method may not be run fully, can you provide an example?

Now you can try to make a debug pointer [here](https://github.com/LinXunFeng/flutter_scrollview_observer/blob/main/lib/src/common/observer_controller.dart#L158), see whether can get there

**Comment by cyb3rsalih** [comment]
I added little timeout and it works. This is not the right way but for now its OK.

**Comment by LinXunFeng** [comment]
Yes, vscode default is to debug the current project code, as shown in the figure

![image](https://user-images.githubusercontent.com/19367531/182890297-bf279d91-81aa-4a00-99b0-d27076a1a6e9.png)

You need to adjust it to `Debug my code + packages + SDK`

![image](https://user-images.githubusercontent.com/19367531/182890385-ae4c4e8c-f536-4150-8e51-945a4db32543.png)

**Comment by cyb3rsalih** [comment]
When I debug the package, saw that hasClients variable returns false. 
It might cause not moving.

Try this code, and still doesn't work
```dart
 WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_scrollController.hasClients) {
        listObserverController.jumpTo(index: 17);
      }
    });
  ```

**Comment by LinXunFeng** [comment]
Maybe you can try the following code

```dart
WidgetsBinding.instance?.endOfFrame.then(
  (_) {
    // After layout
    if (mounted) {
      listObserverController.jumpTo(index: 17);
    }
  },
);
```

Related demo: [listview_demo_page.dart#L26](https://github.com/LinXunFeng/flutter_scrollview_observer/blob/main/example/lib/features/listview/listview_demo/listview_demo_page.dart#L26)

**Comment by LinXunFeng** [comment]
Supported after version [1.8.0](https://github.com/LinXunFeng/flutter_scrollview_observer/releases/tag/1.8.0), the code is as follows

```dart
observerController = ListObserverController(controller: scrollController)
  ..initialIndex = 10;
```
