### ISSUE TITLE
ObserverController.isHandlingScroll  不起作用，被innerReset了，

### ISSUE THREAD

**Issue by xiaodogaa** [LinXunFeng/flutter_scrollview_observer#7]
建议isHandlingScroll为true时，使用 ScrollEndNotification

**Comment by LinXunFeng** [comment]
没明白你的问题点是什么，`isHandlingScroll` 是内部控制是否进行数据处理和触发 `onObserve` 这类回调的，外部不应该对其赋值

**Comment by xiaodogaa** [comment]
/// A flag used to ignore unnecessary calculations during scrolling.
  bool isHandlingScroll = false;
  我看属性是用来 忽略滑动期间的不必要计算，提升性能的；以为设置为true 就可以达到 只有在滑动结束 才触发 onObserve 回调

**Comment by LinXunFeng** [comment]
好吧，我后面改为get方法以避免误用，感谢反馈
