### ISSUE TITLE
如果有SliverAppBar会跳转定位不准确

### ISSUE THREAD

**Issue by zhangruiyu** [LinXunFeng/flutter_scrollview_observer#9]
如果有SliverAppBar会跳转定位不准确
expandedHeight随便填个200
再加个SliverToBoxAdapter这种复杂点场景会出现

**Comment by LinXunFeng** [comment]
感谢反馈，请升级至 `1.3.0` 版本

创建 `SliverAppBar` 并为其绑定 `GlobalKey`
```dart
GlobalKey appBarKey = GlobalKey();

Widget _buildSliverAppBar() {
  return SliverAppBar(
    key: appBarKey,
    pinned: true,
    expandedHeight: 200,
    flexibleSpace: ...,
  );
}
```

调用跳转定位方法时，实现 `offset` 回调

```dart
observerController.animateTo(
  ...
  offset: (offset) {
    return ObserverUtils.calcPersistentHeaderExtent(
      key: appBarKey,
      offset: offset,
    );
  },
);
```

示例代码：[sliver_appbar_demo_page.dart](https://github.com/LinXunFeng/flutter_scrollview_observer/blob/main/example/lib/features/custom_scrollview/sliver_appbar_demo/sliver_appbar_demo_page.dart#L92)

**Comment by zhangruiyu** [comment]
感谢感谢 没毛病啦
